name: ml311
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.17=py311hc665b79_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.3=h3385a95_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libsodium=1.0.20=h4ab18f5_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.6.0=h26f9b46_0
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pip=25.2=pyhc872135_1
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.3=py311haee01d2_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.11.14=h6fa692b_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=2_cp311
  - pyzmq=27.1.0=py311h2315fbb_0
  - readline=8.3=hc2a1206_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.2=py311h49ec1c0_2
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - aiosqlite==0.20.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - anyascii==0.3.3
      - anyio==4.12.0
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - asyncpg==0.29.0
      - attrs==25.4.0
      - audioread==3.1.0
      - av==12.3.0
      - babel==2.17.0
      - bangla==0.0.5
      - beautifulsoup4==4.14.2
      - bleach==6.3.0
      - blinker==1.9.0
      - blis==1.3.3
      - bnnumerizer==0.0.2
      - bnunicodenormalizer==0.1.7
      - catalogue==2.0.10
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - chumpy==0.70
      - click==8.1.7
      - cloudpathlib==0.23.0
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - confection==0.1.5
      - contourpy==1.3.3
      - coqpit==0.0.17
      - crcmod==1.7
      - cryptography==46.0.3
      - ctranslate2==4.6.1
      - cycler==0.12.1
      - cymem==2.0.13
      - cython==3.2.1
      - dateparser==1.1.8
      - defusedxml==0.7.1
      - docopt==0.6.2
      - einops==0.8.1
      - encodec==0.1.1
      - fastapi==0.115.5
      - faster-whisper==1.0.2
      - fastjsonschema==2.21.2
      - filelock==3.14.0
      - flask==2.3.2
      - flatbuffers==25.9.23
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - g2pkk==0.1.2
      - gast==0.6.0
      - google-pasta==0.2.0
      - greenlet==3.2.4
      - grpcio==1.76.0
      - gruut==2.2.3
      - gruut-ipa==0.13.0
      - gruut-lang-de==2.0.1
      - gruut-lang-en==2.0.1
      - gruut-lang-es==2.0.1
      - gruut-lang-fr==2.0.2
      - h11==0.16.0
      - h5py==3.15.1
      - hangul-romanize==0.1.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.27.2
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - idna==3.11
      - inflect==7.5.0
      - itsdangerous==2.2.0
      - jamo==0.4.1
      - jax==0.7.1
      - jaxlib==0.7.1
      - jieba==0.42.1
      - jinja2==3.1.6
      - jmespath==0.10.0
      - joblib==1.5.2
      - json-tricks==3.17.3
      - jsonlines==1.2.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-pygments==0.3.0
      - keras==3.12.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - librosa==0.11.0
      - llvmlite==0.45.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mdurl==0.1.2
      - mediapipe==0.10.21
      - mistune==3.1.4
      - ml-dtypes==0.5.3
      - mmcv==2.1.0
      - mmdet==3.3.0
      - mmengine==0.10.7
      - mmpose==1.3.2
      - model-index==0.1.11
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - munkres==1.1.4
      - murmurhash==1.0.15
      - namex==0.1.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==2.8.8
      - nltk==3.9.2
      - num2words==0.5.14
      - numba==0.62.1
      - numpy==1.26.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.1.105
      - onnxruntime==1.23.2
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.8.0.74
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - opt-einsum==3.4.0
      - optree==0.18.0
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - pillow==12.0.0
      - pooch==1.8.2
      - preshed==3.0.12
      - propcache==0.4.1
      - protobuf==4.25.8
      - pycocotools==2.0.10
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pypinyin==0.55.0
      - pysbd==0.3.4
      - python-crfsuite==0.9.11
      - python-dotenv==1.2.1
      - python-multipart==0.0.9
      - pytz==2023.4
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.28.2
      - rich==13.4.2
      - rpds-py==0.28.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - seaborn==0.13.2
      - sentencepiece==0.2.1
      - setuptools==60.2.0
      - shapely==2.1.2
      - shellingham==1.5.4
      - smart-open==7.5.0
      - sniffio==1.3.1
      - sounddevice==0.5.3
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.44
      - sqlmodel==0.0.22
      - srsly==2.5.2
      - starlette==0.41.3
      - sudachidict-core==20251022
      - sudachipy==0.6.10
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.2.0
      - terminaltables==3.1.10
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.15.2
      - torch==2.3.1+cu121
      - torchaudio==2.3.1+cu121
      - torchvision==0.18.1+cu121
      - tqdm==4.65.2
      - trainer==0.0.36
      - transformers==4.36.2
      - triton==2.3.1
      - tts==0.22.0
      - typeguard==4.4.4
      - typer-slim==0.20.0
      - tzdata==2025.2
      - tzlocal==5.3.1
      - umap-learn==0.5.9.post2
      - unidecode==1.4.0
      - urllib3==1.26.20
      - uvicorn==0.32.0
      - uvloop==0.22.1
      - waitress==3.0.2
      - wasabi==1.1.3
      - watchfiles==1.1.1
      - weasel==0.4.3
      - webencodings==0.5.1
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==2.0.1
      - xtcocotools==1.14.3
      - yapf==0.43.0
      - yarl==1.22.0
prefix: /home/shamika/miniconda3/envs/ml311
